### ISSUE TITLE
Append one configure option to use `HostPath` volume in Cassandra ReplicationController

### ISSUE THREAD

**Issue by harobed** [openshift/origin-metrics#263]
I need one configure option to use `HostPath` volume:

```
        volumes:
        - name: cassandra-data
          hostPath:
            path: /var/volumes/hawkular-cassandra-data/
```
